# Generated by Django 2.0.4 on 2018-04-09 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('anime_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.TextField()),
                ('types', models.CharField(choices=[('Movie', 'Movie'), ('OVA', 'OVA'), ('TV', 'TV')], default='Movie', max_length=5)),
                ('episodes', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('members', models.IntegerField()),
            ],
        ),
    ]
