# Generated by Django 2.0.4 on 2018-04-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programmes',
            new_name='Programme',
        ),
    ]
