# Generated by Django 2.0.4 on 2018-04-10 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20180409_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.TextField()),
                ('types', models.CharField(choices=[('Movie', 'Movie'), ('OVA', 'OVA'), ('TV', 'TV')], default='Movie', max_length=5)),
                ('episodes', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('members', models.IntegerField()),
                ('icon', models.ImageField(null=True, upload_to='img/profiles', verbose_name='Anime Photo')),
            ],
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
