# Generated by Django 2.0.4 on 2018-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_auto_20180410_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
