# Generated by Django 2.0.4 on 2018-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_auto_20180410_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12),
        ),
    ]
