# Generated by Django 2.0.4 on 2018-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_auto_20180410_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
