# Generated by Django 2.0.4 on 2018-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_auto_20180410_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img/profiles/', verbose_name='Anime Photo'),
        ),
    ]
