# Generated by Django 2.0.4 on 2018-04-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_auto_20180411_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='icon',
            field=models.ImageField(blank=True, default='static/profiles/neutralface.png', null=True, upload_to='static/profiles/', verbose_name='Anime Photo'),
        ),
    ]
